### ISSUE TITLE
Shortcuts does not work:

### ISSUE THREAD

**Issue by nrsfhass** [LAB02-Research/HASS.Agent-Notifier#10]
Shortcuts does not work:

2022-04-15 14:28:42.489 -03:00 [INF] [HASS_API] Home Assistant version: 2022.4.4
2022-04-15 14:28:43.193 -03:00 [INF] [HASS_API] System connected with http://192.168.1.98:8123
2022-04-15 14:28:46.225 -03:00 [WRN] [HASS_API] Server returned 404 (not found) while getting entity state. This can happen after a server reboot, or if you've deleted the entity. If the problem persists, please file a ticket on github.
Entity: light.agua
Error message: Response status code does not indicate success: 404 (Not Found).

##############################################################
2022-04-15 14:39:48.882 -03:00 [FTL] [HASS_API] [.agua] Error while processing action: Response status code does not indicate success: 404 (Not Found).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HADotNet.Core.BaseClient.Post[T](String path, Object body, Boolean isRawBody)
   at HADotNet.Core.Clients.ServiceClient.CallService(String serviceName, String fields)
   at HASS.Agent.HomeAssistant.HassApiManager.ProcessActionAsync(HassEntity entity, HassAction action)
2022-04-15 14:39:50.048 -03:00 [WRN] [HASS_API] Server returned 404 (not found) while getting entity state. This can happen after a server reboot, or if you've deleted the entity. If the problem persists, please file a ticket on github.
Entity: light.agua
Error message: Response status code does not indicate success: 404 (Not Found).
2022-04-15 14:39:53.459 -03:00 [INF] [HASS_API] [.agua] Performing action: 
2022-04-15 14:39:53.463 -03:00 [FTL] [HASS_API] [.agua] Error while processing action: Response status code does not indicate success: 404 (Not Found).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HADotNet.Core.BaseClient.Post[T](String path, Object body, Boolean isRawBody)
   at HADotNet.Core.Clients.ServiceClient.CallService(String serviceName, String fields)
   at HASS.Agent.HomeAssistant.HassApiManager.ProcessActionAsync(HassEntity entity, HassAction action)
2022-04-15 14:40:00.637 -03:00 [INF] [HASS_API] [.agua] Performing action: 
2022-04-15 14:40:00.642 -03:00 [FTL] [HASS_API] [.agua] Error while processing action: Response status code does not indicate success: 404 (Not Found).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at HADotNet.Core.BaseClient.Post[T](String path, Object body, Boolean isRawBody)
   at HADotNet.Core.Clients.ServiceClient.CallService(String serviceName, String fields)
   at HASS.Agent.HomeAssistant.HassApiManager.ProcessActionAsync(HassEntity entity, HassAction action)

**Comment by LAB02-Admin** [comment]
[[#47](https://github.com/LAB02-Research/HASS.Agent-Notifier/issues/10)]
