### ISSUE TITLE
Cant Restart Due to Integration Not Found

### ISSUE THREAD

**Issue by I3lackshirts** [LAB02-Research/HASS.Agent-Notifier#28]
Attached is the error message I am getting. I have updated to the newest update and did remove the notifier itegration to convert over to the HASS.Agent itegration.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/81433751/199127695-e469946d-612e-4d5d-ae84-658ff57fad52.png">

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:705
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 5:19:24 PM (3 occurrences)
Last logged: 5:22:43 PM

[546630181424] The system cannot restart because the configuration is not valid: Platform error notify.hass_agent_notifier - Integration 'hass_agent_notifier' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 705, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error notify.hass_agent_notifier - Integration 'hass_agent_notifier' not found.

**Comment by LAB02-Admin** [comment]
Yes that is annoying, I'll write a doc on how to move to the new integration. 

Try removing (or commenting out to test) your `notify` entities you created in yaml. It should reboot afterwards. You can then - if you want - rename the new `notify` entity to the old name, so all your automations will (should) start working again.

Let me know if this works for you
